// Auto-reconstructed: mars_rfspi.c
// Generated by assemble.py — do not edit manually
#include "lib/lmac/mars_rfspi.h"
#include "chip/txw4002ack803/io_function.h"
#include "chip/txw4002ack803/sysctrl.h"
#include "dev.h"
#include "hal/gpio.h"

void ah_rfspi_clear_pd(void) {
    volatile uint32_t *reg = (volatile uint32_t *)0x4001B000;
    uint32_t val = reg[3];  // offset 0xC
    val |= 0x400;          // set bit 10
    reg[3] = val;
}

void ah_rfspi_close(void) {
    volatile uint32_t *reg_base = (volatile uint32_t *)0x4001B000;
    uint32_t val = reg_base[0];
    val &= ~(1U << 8);
    val &= ~(1U << 9);
    reg_base[0] = val;
    val = reg_base[1];
    val &= ~0x07U;
    reg_base[1] = val;
    ah_rfspi_get_pd();
}

uint32_t ah_rfspi_get_pd(void) {
    volatile uint32_t *reg = (volatile uint32_t *)0x4001B000;
    uint32_t val = reg[3];
    return val & 0x400;
}

int ah_rfspi_open(int arg0, uint32_t arg1, uint32_t arg2) {
    volatile uint32_t *syscon = (volatile uint32_t *)0x40026000;
    uint32_t tmp = syscon[5];
    tmp |= 0x8000;
    syscon[5] = tmp;
    tmp = syscon[2];
    tmp &= ~(1U << 25);
    syscon[2] = tmp;
    tmp = syscon[2];
    tmp |= (1U << 25);
    syscon[2] = tmp;
    volatile uint32_t *rfspi = (volatile uint32_t *)0x4001b000;
    uint32_t config_val;
    if (arg0 != 0) {
        config_val = 0x040f03cc;
    } else {
        config_val = 0x040f038c;
    }
    rfspi[0] = config_val;
    tmp = rfspi[1];
    tmp |= 4;
    rfspi[1] = tmp;
    rfspi_pin_func(arg2);
    int ret = ah_rfspi_set_clk((uint8_t)arg1);
    int result = ret;
    uint32_t apbclk = sys_get_apbclk();
    uint32_t calc = (apbclk >> 31) + apbclk;
    calc >>= 1;
    uint32_t mul = arg1 * 1000000;
    int call_arg = (mul != calc) ? 0 : 1;
    ah_rfspi_set_trig_mode((uint32_t)call_arg);
    return result;
}

uint16_t ah_rfspi_read(uint16_t reg_addr) {
    volatile uint32_t *rfspi_base = (volatile uint32_t *)0x4001B000;
    uint32_t reg_val;
    reg_val = rfspi_base[1];
    reg_val &= ~(1U << 3);
    rfspi_base[1] = reg_val;
    reg_val = rfspi_base[1];
    reg_val |= 3U;
    rfspi_base[1] = reg_val;
    rfspi_base[8] = 1U;
    rfspi_base[9] = 0U;
    rfspi_base[4] = ((uint32_t)reg_addr << 16) & 0x7FFF0000U;
    while ((rfspi_base[3] & 0x400U) == 0) {}
    reg_val = rfspi_base[1];
    reg_val |= 8U;
    rfspi_base[1] = reg_val;
    return (uint16_t)rfspi_base[5];
}

int ah_rfspi_set_clk(uint8_t clk_div) {
    uint32_t apb_clk = sys_get_apbclk();
    volatile uint32_t *reg = (volatile uint32_t *)0x4001B000;
    uint32_t val = *reg;
    val &= 0xFF00FFFFu;
    *reg = val;
    uint32_t base_freq = 62500u * 32u;
    uint32_t div = apb_clk / (base_freq * (uint32_t)clk_div);
    div &= 0xFFu;
    div -= 1;
    val = *reg;
    val |= (div << 16);
    *reg = val;
    return 0;
}

int32_t ah_rfspi_set_rx_dly(uint32_t delay) {
    if (delay >= 8) {
        return -1;
    }
    volatile uint32_t *reg = (volatile uint32_t *)0x4001B000;
    uint32_t val = *reg;
    val &= 0xF8FFFFFF;  // clear bits 24-26
    *reg = val;
    val = *reg;
    val |= (delay << 24);
    *reg = val;
    return 0;
}

int ah_rfspi_set_trig_mode(uint32_t mode) {
    volatile uint32_t *reg = (volatile uint32_t *)0x4001B000;
    uint32_t val = *reg;
    val &= ~(1U << 1);
    *reg = val;
    val = *reg;
    val |= (mode << 1);
    *reg = val;
    return 0;
}

void ah_rfspi_write(uint16_t addr, uint32_t data) {
    volatile uint32_t *reg_base = (volatile uint32_t *)0x4001B000;
    uint32_t reg_val;
    uint32_t timeout;
    
    reg_val = reg_base[1];
    reg_val &= ~(1U << 3);
    reg_base[1] = reg_val;
    
    reg_val = reg_base[1];
    reg_val &= ~(1U << 0);
    reg_val &= ~(1U << 1);
    reg_base[1] = reg_val;
    
    reg_val = reg_base[1];
    reg_val |= (1U << 1);
    reg_base[1] = reg_val;
    
    reg_base[8] = 1U;
    reg_base[9] = 0U;
    
    data &= 0x7FFFFFFFU;
    data |= (1U << 31);
    data |= ((uint32_t)addr << 16);
    
    reg_base[4] = data;
    
    timeout = 128U << 9;
    while (1) {
        if (reg_base[3] & (1U << 10)) {
            break;
        }
        timeout--;
        if (timeout == 0) {
            break;
        }
    }
    
    reg_val = reg_base[1];
    reg_val |= (1U << 3);
    reg_base[1] = reg_val;
}

void ah_rfspi_write_and_read(uint32_t arg0) {
    // uint32_t r4 = arg0;
    // ah_rfspi_write_and_read(r4);
    // ah_rfspi_write_and_read(r4);
}

void rfspi_pin_func(uint32_t mode) {
    volatile uint32_t *reg = (volatile uint32_t *)0x40026000;
    uint32_t val = *reg;
    if (mode == 1) {
        val |= (1U << 21);
        *reg = val;
        val = *reg;
        val &= ~(1U << 22);
        *reg = val;
        gpio_set_altnt_func(22, 3);
        gpio_set_altnt_func(23, 3);
        gpio_set_altnt_func(24, 3);
        gpio_set_altnt_func(25, 3);
        return;
    }
    val &= ~(1U << 21);
    *reg = val;
    val = *reg;
    if (mode == 2) {
        val &= ~(1U << 22);
        *reg = val;
        gpio_set_altnt_func(22, 4);
        gpio_set_altnt_func(23, 4);
        gpio_set_altnt_func(24, 4);
        gpio_set_altnt_func(25, 4);
        return;
    }
    if (mode == 3) {
        val |= (1U << 22);
        *reg = val;
        gpio_set_altnt_func(22, 1);
        gpio_set_altnt_func(23, 1);
        gpio_set_altnt_func(24, 1);
        gpio_set_altnt_func(25, 1);
        return;
    }
    val &= ~(1U << 22);
    *reg = val;
    gpio_set_dir(22, 0);
    gpio_set_dir(23, 0);
    gpio_set_dir(24, 0);
    gpio_set_dir(25, 0);
}
