#include "lib/lmac/mars_lmac_tx.h"

#define WRAP(ret, fn, decl, call) extern ret fn##_orig decl; ret fn decl { return fn##_orig call; }
#define WRAPV(fn, decl, call) extern void fn##_orig decl; void fn decl { fn##_orig call; }

/* COMMENTED OUT WRAP macros for functions that now have C implementations in mars_lmac_tx.c
 * This allows the C implementations to be used instead of the original assembly */

WRAP(uint32, lmac_txsq_count, (void), ())
WRAP(uint32, lmac_statq_count, (void), ())
WRAP(uint32, lmac_txq_count, (void), ())
WRAP(uint32, lmac_acq_count, (uint32 ac), (ac))
WRAP(uint32, lmac_txagg_count, (uint32 ac), (ac))
WRAPV(lmac_kick_tx_task, (void), ())
WRAPV(lmac_tx_vec_init, (void), ())
WRAPV(lmac_tx_queue_agglist_init, (void), ())
WRAP(int32, lmac_ah_tx, (struct lmac_ops *ops, struct sk_buff *skb), (ops, skb))
//WRAPV(lmac_tx_init, (void), ())  /* Already commented out - using C implementation */
//WRAP(uint8_t *, lmac_gen_tx_agglist,(uint param_1, uint param_2, uint param_3, uint param_4),(param_1, param_2, param_3, param_4))
WRAP(int32, lmac_ah_test_tx, (struct lmac_ops *ops, struct sk_buff *skb), (ops, skb))
//WRAP(int32, lmac_send_data_to_phy, (uint32 ac), (ac))
WRAP(int32, lmac_beacon_add_s1g_beacon_compatibility, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_beacon_build_s1gbeacon, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_ba, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_ack, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_cts, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_rts, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_pv0_null, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_pv0_pspoll, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_pv0_cfpoll, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_pv0_cfend, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_frm, (struct sk_buff *skb), (skb))
WRAP(int32, lmac_tx_beacon, (struct sk_buff *skb), (skb))
WRAP(void *, lmac_gen_txvec, (uint32 ac, uint32 ac_hint, uint32 mcs), (ac, ac_hint, mcs))
WRAP(int32, lmac_cfg_txvec_part1, (void), ())
WRAPV(lmac_ant_sel, (uint32 ant), (ant))
//WRAP(int32, lmac_cfg_txvec_part2, (void), ())
WRAP(int32, lmac_update_frm_tx_vec, (void), ())
WRAP(int32, lmac_update_ndp_cts_tx_vec, (uint32 arg0, uint32 arg1), (arg0, arg1))
WRAP(int32, lmac_update_ndp_ack_tx_vec, (uint32 arg0, uint32 arg1), (arg0, arg1))
WRAP(int32, lmac_update_ndp_ba_tx_vec, (uint32 arg0, uint32 arg1), (arg0, arg1))
WRAP(int32, lmac_update_pv0_wpba_tx_vec, (void), ())
WRAP(int32, lmac_update_pv0_wpack_tx_vec, (void), ())
WRAP(int32, lmac_update_pv0_wpcts_tx_vec, (void), ())
WRAP(int32, lmac_update_pv0_cfend_tx_vec, (void), ())
WRAPV(ndp_tx_vec_init, (void), ())
WRAP(uint32, pv0_ctrl_uplink_txpwr_gen, (void), ())
WRAPV(lmac_irq_tx_end, (void), ())
WRAPV(lmac_irq_tx_tmo, (void), ())
//WRAPV(lmac_irq_bo_fns, (void), ())
//WRAPV(lmac_irq_ac_pd, (void), ())
WRAP(int32, lmac_update_tx_rate, (uint32 ac, uint8 *rate_out, uint8 *bw_out), (ac, rate_out, bw_out))
WRAP(int32, lmac_update_tx_state_ack, (uint32 ok, uint32 arg1, uint32 arg2), (ok, arg1, arg2))
WRAP(int32, lmac_update_tx_state_ba, (uint32 start_ssn, uint32 bitmap_lo, uint32 bitmap_hi), (start_ssn, bitmap_lo, bitmap_hi))
WRAP(int32, lmac_update_tx_state_cts, (uint32 ok), (ok))
WRAP(int32, ndp_ack_rx_hdl, (uint32 rx0, uint32 rx1, uint32 ext), (rx0, rx1, ext))
WRAP(int32, ndp_ba_rx_hdl, (uint32 rx0, uint32 rx1, uint32 ext), (rx0, rx1, ext))
WRAP(int32, ndp_pspoll_ack_rx_hdl, (void), ())
WRAP(uint32, lmac_select_resp_ind, (void), ())
WRAPV(lmac_pv0_rts_init, (void), ())
WRAPV(lmac_pv0_wpack_init, (void), ())
WRAPV(lmac_pv0_wpcts_init, (void), ())
WRAPV(lmac_pv0_wpba_init, (void), ())
WRAPV(lmac_pv0_cfpoll_init, (void), ())
WRAPV(lmac_pv0_pspoll_init, (void), ())
WRAPV(lmac_pv0_cfend_init, (void), ())
WRAPV(lmac_pv0_qos_null_init, (void), ())
WRAP(int32, lmac_reorder_tx_agglist, (void), ())
WRAP(struct sk_buff *, lmac_get_first_skb, (uint32 ac), (ac))
WRAP(uint32, lmac_get_ack_policy, (void *txi), (txi))
WRAP(uint32, lmac_select_tx_acq, (void), ())
WRAP(int32, tx_skbs_cached, (void), ())
WRAP(int32, lmac_tx_pwr_sel, (void *txi, uint32 mcs), (txi, mcs))
WRAPV(lmac_spec_cca_cfg, (uint32 enable), (enable))
WRAPV(lmac_adjust_cca_threshold, (int32 delta), (delta))
WRAPV(lmac_adjust_agc_threshold, (int32 level), (level))
WRAPV(lmac_bknoise_calc_en, (void), ())
WRAPV(lmac_bknoise_calc_dis, (void), ())
WRAP(uint32, lmac_bknoise_valid_pd_get, (void), ())
WRAPV(lmac_bknoise_valid_pd_clr, (void), ())
WRAP(uint32, lmac_bknoise_get, (void), ())
WRAPV(lmac_bgrssi_update, (void), ())
WRAP(int32, lmac_send_mgmt_meas_req, (void), ())
WRAP(int32, lmac_send_mgmt_meas_report, (void), ())
WRAP(int32, lmac_send_bss_announcement, (void), ())
WRAP(int32, lmac_send_scan_probe, (void), ())
WRAP(int32, lmac_send_ant_pkt, (void), ())
WRAP(int32, lmac_send_probe_resp, (void), ())
WRAP(int32, lmac_tx_frame_regen, (uint32 ac, uint32 ac_hint, uint32 mcs, void *arg), (ac, ac_hint, mcs, arg))
WRAP(int32, lmac_tx_date_prepared, (void), ())
WRAPV(lmac_partial_aid_update, (void *txi), (txi))
WRAP(uint32, lmac_dtim_timer_rem, (void), ())
WRAP(uint32, lmac_hdr_dur_calc, (uint32 len), (len))
WRAP(int32, lmac_tx_to_pm_ap, (void), ())
WRAPV(switch_ctrl_normal_mode, (void), ())
WRAPV(switch_ctrl_recover, (void), ())
WRAP(int32, lmac_auto_channel_select, (void), ())
WRAP(uint32, lmac_vht_info_get, (uint32 info), (info))
WRAP(void *, get_worst_node, (void), ())
WRAP(uint64, lmac_gen_pspack_ndp2m, (void), ())
WRAP(uint64, lmac_gen_pspoll_ndp2m, (void), ())
WRAP(uint64, lmac_gen_pspoll_ack_ndp2m, (void), ())
/* Static in original binary — implemented in mars_lmac_tx.c */
//WRAPV(lmac_tx_pv0_s1g_beacon, (struct sk_buff *skb), (skb))
//WRAPV(lmac_tx_data_reload, (void), ())
//WRAP(int32, lmac_check_aggregation, (struct sk_buff *skb0, struct sk_buff *skb1), (skb0, skb1))
//WRAP(uint32, seq_num_space_update, (void *sta, uint32 tid), (sta, tid))
//WRAP(int32, lmac_tx_queue_init, (void), ())
//WRAP(int32, lmac_tx_pv0_mgmt, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv0_ctrl, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv0_data, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv0_ext, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv1_data1, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv1_mgmt, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv1_ctrl, (struct sk_buff *skb), (skb))
//WRAP(int32, lmac_tx_pv1_data2, (struct sk_buff *skb), (skb))

#undef WRAP
#undef WRAPV
