#ifndef __RNS_DEFINES_H__
#define __RNS_DEFINES_H__


#define RNS_TRUNCATED_HASH_LEN    (16U)
#define RNS_LINK_ID_LEN           RNS_TRUNCATED_HASH_LEN
#define RNS_LINKREQUEST_CORE_LEN  (64U)

typedef enum {
    RNS_LINK_PARSER_PACKET_DATA        = 0x00U,
    RNS_LINK_PARSER_PACKET_ANNOUNCE    = 0x01U,
    RNS_LINK_PARSER_PACKET_LINKREQUEST = 0x02U,
    RNS_LINK_PARSER_PACKET_PROOF       = 0x03U
} rns_packet_type_t;

typedef enum {
    RNS_LINK_PARSER_HEADER_1 = 0x00U,
    RNS_LINK_PARSER_HEADER_2 = 0x01U
} rns_header_type_t;

typedef enum {
    RNS_LINK_PARSER_DESTINATION_SINGLE = 0x00U,
    RNS_LINK_PARSER_DESTINATION_GROUP  = 0x01U,
    RNS_LINK_PARSER_DESTINATION_PLAIN  = 0x02U,
    RNS_LINK_PARSER_DESTINATION_LINK   = 0x03U
} rns_destination_type_t;

typedef enum {
    RNS_LINK_PARSER_CONTEXT_NONE         = 0x00U,
    RNS_LINK_PARSER_CONTEXT_KEEPALIVE    = 0xFAU,
    RNS_LINK_PARSER_CONTEXT_LINKIDENTIFY = 0xFBU,
    RNS_LINK_PARSER_CONTEXT_LINKCLOSE    = 0xFCU,
    RNS_LINK_PARSER_CONTEXT_LINKPROOF    = 0xFDU,
    RNS_LINK_PARSER_CONTEXT_LRRTT        = 0xFEU,
    RNS_LINK_PARSER_CONTEXT_LRPROOF      = 0xFFU
} rns_context_t;


#endif // __RNS_DEFINES_H__
